version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo-container
    network_mode: host
    healthcheck:
      test: "exit 0"

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    container_name: mysql-container
    healthcheck:
      test: "exit 0"
    environment:
      MYSQL_ROOT_PASSWORD: Root@123
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: NoteDB
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    network_mode: host
    

  config-service:
    image: config-service
    build: config-service/
    network_mode: host
    container_name: config-service
    healthcheck:
      test: "exit 0"
    ports:
      - "8888:8888"

  donation-service:
    image: donation-service
    build: donation-service/
    network_mode: host
    container_name: donation-service
    healthcheck:
      test: "exit 0"
    ports:
      - "8090:8090"
    depends_on:
      - mongodb
      - config-service
      - eureka-service
      - zuul-service

  environment-service:
    image: environment-service
    build: environment-service/
    network_mode: host
    container_name: environment-service
    healthcheck:
      test: "exit 0"
    ports:
      - "8091:8091"
    depends_on:
      - mongodb
      - config-service
      - eureka-service
      - zuul-service

  eureka-service:
    image: eureka-service
    build: eureka-service/
    network_mode: host
    container_name: eureka-service
    healthcheck:
      test: "exit 0"
    ports:
      - "8761:8761"

  #TODO FREX UI
  frex-ui:
    image: frex-ui
    build: frex-ui/
    ports:
      - "4200:4200"
    container_name: frex-ui
    network_mode: host

  partners-service:
    image: partners-service
    build: partners-service/
    network_mode: host
    container_name: partners-service
    healthcheck:
      test: "exit 0"
    depends_on:
      - mongodb
      - eureka-service
      - config-service
      - zuul-service
    ports:
      - "8092:8092"

  userprofile-service:
    image: userprofile-service
    build: userprofile-service/
    network_mode: host
    container_name: userprofile-service
    healthcheck:
      test: "exit 0"
    depends_on:
      - mongodb
      - eureka-service
      - config-service
      - zuul-service
    ports:
      - "8093:8093"

  verification-service:
    image: verification-service
    build: verification-service/
    network_mode: host
    container_name: verification-service
    healthcheck:
      test: "exit 0"
    depends_on:
      - mysql
      - eureka-service
      - config-service
      - zuul-service
    ports:
      - "8094:8094"

  zuul-service:
    image: zuul-service
    build: zuul-service/
    network_mode: host
    container_name: zuul-service
    healthcheck:
      test: "exit 0"
    ports:
      - "8081:8081"

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    expose:
      - "2181"

  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: “Ticketdetails:1”

  rewards-service:
    image: rewards-service
    build: rewards-service/
    network_mode: host
    container_name: rewards-service
    healthcheck:
      test: "exit 0"
    ports:
      - "8095:8095"
    depends_on:
      - mongodb
      - config-service
      - eureka-service
      - zuul-service
      - kafka
  
  fitness-service:
    image: fitness-service
    build: fitness-service/
    network_mode: host
    container_name: fitness-service
    healthcheck:
      test: "exit 0"
    ports: 
      - "8089:8089"
    depends_on: 
      - mongodb
      - config-service
      - eureka-service
      - zuul-service
      - kafka


